[build]
  base = "frontend"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "22.16.0"
  NPM_VERSION = "10.8.1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production.environment]
  VITE_API_BASE_URL = "https://udyam-backend.onrender.com"
  VITE_API_VERSION = "v1"
  VITE_APP_ENVIRONMENT = "production"
  VITE_ENABLE_DEBUG_MODE = "false"
  VITE_DEFAULT_LANGUAGE = "en"
  VITE_SUPPORTED_LANGUAGES = "en,hi"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://udyam-backend-staging.onrender.com"
  VITE_API_VERSION = "v1"
  VITE_APP_ENVIRONMENT = "staging"
  VITE_ENABLE_DEBUG_MODE = "true"
  VITE_DEFAULT_LANGUAGE = "en"
  VITE_SUPPORTED_LANGUAGES = "en,hi"
