services:
  # Frontend Service
  - type: web
    name: udyam-frontend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./frontend/dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Permissions-Policy
        value: geolocation=(), camera=(), microphone=()
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_BASE_URL
        value: https://udyam-backend.onrender.com
      - key: VITE_API_VERSION
        value: v1
      - key: VITE_APP_ENVIRONMENT
        value: production
      - key: VITE_ENABLE_DEBUG_MODE
        value: false
      - key: VITE_DEFAULT_LANGUAGE
        value: en
      - key: VITE_SUPPORTED_LANGUAGES
        value: en,hi

  # Backend Service  
  - type: web
    name: udyam-backend
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://udyam-frontend.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: DATABASE_URL
        fromDatabase:
          name: udyam-database
          property: connectionString

databases:
  - name: udyam-database
    databaseName: udyam
    user: udyam_user
    plan: free
